language: haskell

before_install:
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update

  # Try installing some of the build-deps with apt-get for speed.
  - travis/cabal-apt-install 


install:
  - $CABAL install --dependencies-only 
  - $CABAL configure 
  - $CABAL build
